/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as AppWithdrawRouteImport } from './routes/app.withdraw'
import { Route as AppWheelRouteImport } from './routes/app.wheel'
import { Route as AppWalletRouteImport } from './routes/app.wallet'
import { Route as AppVaultRouteImport } from './routes/app.vault'
import { Route as AppReferralRouteImport } from './routes/app.referral'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppDepositRouteImport } from './routes/app.deposit'
import { Route as ApiPublicWebhooksNotchpayRouteImport } from './routes/api/public/webhooks/notchpay'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWithdrawRoute = AppWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppRoute,
} as any)
const AppWheelRoute = AppWheelRouteImport.update({
  id: '/wheel',
  path: '/wheel',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultRoute = AppVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralRoute = AppReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositRoute = AppDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicWebhooksNotchpayRoute =
  ApiPublicWebhooksNotchpayRouteImport.update({
    id: '/api/public/webhooks/notchpay',
    path: '/api/public/webhooks/notchpay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/profile': typeof AppProfileRoute
  '/app/referral': typeof AppReferralRoute
  '/app/vault': typeof AppVaultRoute
  '/app/wallet': typeof AppWalletRoute
  '/app/wheel': typeof AppWheelRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/r/$code': typeof RCodeRoute
  '/app/': typeof AppIndexRoute
  '/api/public/webhooks/notchpay': typeof ApiPublicWebhooksNotchpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/profile': typeof AppProfileRoute
  '/app/referral': typeof AppReferralRoute
  '/app/vault': typeof AppVaultRoute
  '/app/wallet': typeof AppWalletRoute
  '/app/wheel': typeof AppWheelRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/r/$code': typeof RCodeRoute
  '/app': typeof AppIndexRoute
  '/api/public/webhooks/notchpay': typeof ApiPublicWebhooksNotchpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/profile': typeof AppProfileRoute
  '/app/referral': typeof AppReferralRoute
  '/app/vault': typeof AppVaultRoute
  '/app/wallet': typeof AppWalletRoute
  '/app/wheel': typeof AppWheelRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/r/$code': typeof RCodeRoute
  '/app/': typeof AppIndexRoute
  '/api/public/webhooks/notchpay': typeof ApiPublicWebhooksNotchpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/app/deposit'
    | '/app/profile'
    | '/app/referral'
    | '/app/vault'
    | '/app/wallet'
    | '/app/wheel'
    | '/app/withdraw'
    | '/r/$code'
    | '/app/'
    | '/api/public/webhooks/notchpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/app/deposit'
    | '/app/profile'
    | '/app/referral'
    | '/app/vault'
    | '/app/wallet'
    | '/app/wheel'
    | '/app/withdraw'
    | '/r/$code'
    | '/app'
    | '/api/public/webhooks/notchpay'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/app/deposit'
    | '/app/profile'
    | '/app/referral'
    | '/app/vault'
    | '/app/wallet'
    | '/app/wheel'
    | '/app/withdraw'
    | '/r/$code'
    | '/app/'
    | '/api/public/webhooks/notchpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  RCodeRoute: typeof RCodeRoute
  ApiPublicWebhooksNotchpayRoute: typeof ApiPublicWebhooksNotchpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/withdraw': {
      id: '/app/withdraw'
      path: '/withdraw'
      fullPath: '/app/withdraw'
      preLoaderRoute: typeof AppWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wheel': {
      id: '/app/wheel'
      path: '/wheel'
      fullPath: '/app/wheel'
      preLoaderRoute: typeof AppWheelRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vault': {
      id: '/app/vault'
      path: '/vault'
      fullPath: '/app/vault'
      preLoaderRoute: typeof AppVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/referral': {
      id: '/app/referral'
      path: '/referral'
      fullPath: '/app/referral'
      preLoaderRoute: typeof AppReferralRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deposit': {
      id: '/app/deposit'
      path: '/deposit'
      fullPath: '/app/deposit'
      preLoaderRoute: typeof AppDepositRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/webhooks/notchpay': {
      id: '/api/public/webhooks/notchpay'
      path: '/api/public/webhooks/notchpay'
      fullPath: '/api/public/webhooks/notchpay'
      preLoaderRoute: typeof ApiPublicWebhooksNotchpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDepositRoute: typeof AppDepositRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReferralRoute: typeof AppReferralRoute
  AppVaultRoute: typeof AppVaultRoute
  AppWalletRoute: typeof AppWalletRoute
  AppWheelRoute: typeof AppWheelRoute
  AppWithdrawRoute: typeof AppWithdrawRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDepositRoute: AppDepositRoute,
  AppProfileRoute: AppProfileRoute,
  AppReferralRoute: AppReferralRoute,
  AppVaultRoute: AppVaultRoute,
  AppWalletRoute: AppWalletRoute,
  AppWheelRoute: AppWheelRoute,
  AppWithdrawRoute: AppWithdrawRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  RCodeRoute: RCodeRoute,
  ApiPublicWebhooksNotchpayRoute: ApiPublicWebhooksNotchpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
